config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reception.urls", namespace="reception")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("users/", include("users.urls", namespace="user")),
]

reception/urls.py
from django.urls import path

from .views import (
    index,
    VisitListView,
    VisitDetailView,
    VisitCreateView,
    VisitUpdateView,
    VisitDeleteView,
)

app_name = "reception"

urlpatterns = [
    path("", index, name="index"),
    path("visits/", VisitListView.as_view(), name="visit-list"),
    path("visits/<int:pk>/", VisitDetailView.as_view(), name="visit-detail"),
    path("visits/create/", VisitCreateView.as_view(), name="visit-create"),
    path(
        "visits/<int:pk>/update/",
        VisitUpdateView.as_view(),
        name="visit-update",
    ),
    path(
        "visits/<int:pk>/delete/",
        VisitDeleteView.as_view(),
        name="visit-delete",
    ),
]

users/urls.py
from django.urls import path

from .views import (
    PatientListView,
    PatientDetailView,
    PatientCreateView,
    PatientUpdateView,
    PatientDeleteView,
    DoctorListView,
    DoctorDetailView,
    DoctorCreateView,
    DoctorUpdateView,
    DoctorDeleteView,
)

app_name = "user"

urlpatterns = [
    path("patients/", PatientListView.as_view(), name="patient-list"),
    path(
        "patients/<int:pk>/",
        PatientDetailView.as_view(),
        name="patient-detail",
    ),
    path(
        "patients/create/", PatientCreateView.as_view(), name="patient-create"
    ),
    path(
        "patients/<int:pk>/update/",
        PatientUpdateView.as_view(),
        name="patient-update",
    ),
    path(
        "patients/<int:pk>/delete/",
        PatientDeleteView.as_view(),
        name="patient-delete",
    ),
    path("doctors/", DoctorListView.as_view(), name="doctor-list"),
    path(
        "doctors/<int:pk>/", DoctorDetailView.as_view(), name="doctor-detail"
    ),
    path("doctors/create/", DoctorCreateView.as_view(), name="doctor-create"),
    path(
        "doctors/<int:pk>/update/",
        DoctorUpdateView.as_view(),
        name="doctor-update",
    ),
    path(
        "doctors/<int:pk>/delete/",
        DoctorDeleteView.as_view(),
        name="doctor-delete",
    ),
]

reception/models.py
from datetime import datetime

from django.db import models
from django.conf import settings

from users.models import Patient, Specialization
from utils.models import SoftDeleteModel

VISIT_CHOICES = (
    ("INIT", "Initial"),
    ("REPT", "Repeat"),
)


class Visit(SoftDeleteModel):
    treatment_direction = models.ForeignKey(
        Specialization,
        null=True,
        on_delete=models.SET_NULL,
    )
    date_time = models.DateTimeField(default=datetime.now)
    doctor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL,
        related_name="visits",
    )
    type_of_visit = models.CharField(
        max_length=4,
        choices=VISIT_CHOICES,
        default="REPT",
    )
    patient = models.ForeignKey(
        Patient, null=True, on_delete=models.SET_NULL, related_name="visits"
    )

    class Meta:
        ordering = ("date_time",)

reception/forms.py
from datetime import datetime

from django import forms
from django.core.exceptions import ValidationError

from reception.models import Visit


class VisitForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = (
            "patient",
            "date_time",
            "treatment_direction",
            "doctor",
            "type_of_visit",
        )

    def clean_date_time(self):
        return validate_date_time(self.cleaned_data["date_time"])


def validate_date_time(date_time):
    """
    Check the visit date field.
    The visit date must be greater than the current date. Timezone-aware!
    """
    queryset = (
        Visit.objects.select_related(
            "treatment_direction", "doctor", "patient"
        )
        .filter(patient__deleted_at__isnull=True)
        .filter(doctor__deleted_at__isnull=True)
        .filter(date_time__gte=datetime.now(date_time.tzinfo))
    )
    for visit in queryset:
        if date_time == visit.date_time:
            raise ValidationError(
                f"{visit.doctor} already has an entry for this date and time. "
                "Please select another date/time or doctor."
            )

    if date_time <= datetime.now(date_time.tzinfo):
        raise ValidationError(
            "The visit date is overdue. Enter a visit date "
            "greater than the current one in YYYY-MM-DD format."
        )

    return date_time


class VisitSearchForm(forms.Form):
    date_time = forms.CharField(
        max_length=10,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by date or time"}
        ),
    )

reception/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from reception.forms import VisitSearchForm, VisitForm
from reception.models import Visit
from users.models import Patient, Doctor


@login_required
def index(request):
    """
    View function for the home page of the site.
    """
    num_visits = (
        Visit.objects.filter(deleted_at__isnull=True)
        .filter(date_time__gte=datetime.now())
        .count()
    )
    num_patients = Patient.objects.filter(deleted_at__isnull=True).count()
    num_doctors = (
        Doctor.objects.filter(is_staff=False)
        .filter(deleted_at__isnull=True)
        .count()
    )

    num_visit_page = request.session.get("num_visit_page", 0) + 1
    request.session["num_visit_page"] = num_visit_page

    context = {
        "num_patients": num_patients,
        "num_visits": num_visits,
        "num_doctors": num_doctors,
        "num_visit_page": num_visit_page,
        "is_show_counter": True,
    }

    return render(request, "reception/index.html", context=context)


class VisitListView(LoginRequiredMixin, generic.ListView):
    model = Visit
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(VisitListView, self).get_context_data(**kwargs)
        date_time = self.request.GET.get("date_time", "")
        context["search_form"] = VisitSearchForm(
            initial={"date_time": date_time}
        )
        return context

    def get_queryset(self):
        queryset = (
            Visit.objects.select_related(
                "treatment_direction", "doctor", "patient"
            )
            .filter(patient__deleted_at__isnull=True)
            .filter(doctor__deleted_at__isnull=True)
            .filter(date_time__gte=datetime.now())
        )
        form = VisitSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                date_time__icontains=form.cleaned_data["date_time"]
            )

        return queryset


class VisitDetailView(LoginRequiredMixin, generic.DetailView):
    model = Visit
    queryset = (
        Visit.objects.select_related(
            "treatment_direction",
            "doctor",
            "patient",
        )
        .filter(patient__deleted_at__isnull=True)
        .filter(doctor__deleted_at__isnull=True)
    )


class VisitCreateView(LoginRequiredMixin, generic.CreateView):
    model = Visit
    form_class = VisitForm
    success_url = reverse_lazy("reception:visit-list")


class VisitUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Visit
    form_class = VisitForm
    success_url = reverse_lazy("reception:visit-list")


class VisitDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Visit
    success_url = reverse_lazy("reception:visit-list")

templates/reception/index.html
{% extends "base.html" %}

{% block title %}<title>Home • ToTheDoctor</title>{% endblock %}

{% block content %}
<br>

<div class="alert alert-light text-center">
  <small>Welcome <strong>ToTheDoctor</strong>. This is a system for planning and
    recording patient visits to the doctors</small>
</div>

<div class="alert alert-dark">
  <p class="mb-0 text-center">So let's get started...</p>
  <br>
  <h4 class="alert-heading text-center">What do you want to do?</h4>
</div>

<br>
<hr class="featurette-divider">
<br>

<div class="container marketing text-center">
  <div class="row">
    <div class="col-lg-4">
      <a href="{% url 'user:patient-create' %}" type="button" class="btn btn-light">
        <img src="/static/image/create_patient.png" width="90" height="90">
      </a>
      <h4 class="fw-normal">Create a patient</h4>
      <p>Create a new patient and see the more details</p>
      <div class="alert alert-warning" role="alert">
        You have <strong>{{ num_patients }}</strong> patient{{ num_doctors|pluralize }} in your base
      </div>
    </div>
    <div class="col-lg-4">
      <a href="{% url 'reception:visit-create' %}" type="button" class="btn btn-light">
        <img src="/static/image/create_visit.png" width="90" height="90">
      </a>
      <h4 class="fw-normal">Create a visit</h4>
      <p>Create a new visit and see the more details</p>
      <div class="alert alert-warning" role="alert">
        You have <strong>{{ num_visits }}</strong> visit{{ num_visits|pluralize }} in your base
      </div>
    </div>
    <div class="col-lg-4">
      <a href="{% url 'user:doctor-list' %}" type="button" class="btn btn-light">
        <img src="/static/image/create_doctor.png" width="90" height="90">
      </a>
      <h4 class="fw-normal">Find a doctor</h4>
      <p>Open the doctor's card and see the details</p>
      <div class="alert alert-warning" role="alert">
        You have <strong>{{ num_doctors }}</strong> doctor{{ num_patients|pluralize }} in your base
      </div>
    </div>

  </div>
</div>

{% endblock %}

templates/reception/visit_confirm_delete.html
{% extends "base.html" %}

{% block title %}<title>Visit confirm delete • ToTheDoctor</title>{% endblock %}

{% block content %}
  <br>
  <a href="{% url 'reception:visit-detail' pk=visit.id %}" class="btn btn-outline-primary">
    < Back
  </a>

  <div class="px-4 pt-5 my-5 text-center border-top border-bottom">
    <h1 class="display-4 fw-bold text-body-emphasis">
      Do you want to delete all visit information?
    </h1>
    <br>

    <div class="col-lg-6 mx-auto">
      <p>Visit:
        <span class="text-muted">{{ visit.date_time }}</span>
      </p>

      <div class="col-lg-10 mx-auto">
        <p>Doctor:
          <span class="text-muted">{{ visit.doctor }}</span>
        </p>

        <p>Patient:
          <span class="text-muted">{{ visit.patient }}</span>
        </p>

        <p>Type of visit:
          <span class="text-muted">{{ visit.get_type_of_visit_display }}, {{ visit.treatment_direction }}</span>
        </p>
        <br>

        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
          <form action="" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Yes, delete">
          </form>
        </div>

      </div>
    </div>
  </div>

{% endblock %}

templates/reception/visit_detail.html
{% extends "base.html" %}

{% block title %}<title>Visit details • ToTheDoctor</title>{% endblock %}

{% block content %}
  <br>
  <a href="{% url 'reception:visit-list' %}" class="btn btn-outline-primary">
    < Back
  </a>

  <div class="px-4 pt-5 my-5 text-center border-top border-bottom">
    <h1 class="display-4 fw-bold text-body-emphasis">
      Visit planned:
      <span class="text-muted">{{ visit.date_time }}</span>
    </h1>
    <br>


    <div class="col-lg-6 mx-auto">
      <p>Doctor:
        <a href="{% url 'user:doctor-detail' pk=visit.doctor.id %}" class="text-warning">
         {{ visit.doctor }}
        </a>
      </p>
      <br>

      <p>Patient:
        <a href="{% url 'user:patient-detail' pk=visit.patient.id %}" class="text-warning">
          {{ visit.patient }}
        </a>
      </p>
      <br>

      <p class="font-weight-light text-muted">Type of visit:
        <span class="font-weight-normal">{{ visit.get_type_of_visit_display }}, {{ visit.treatment_direction }}</span>
      </p>

      <br>
      <br>
      <br>
      <br>
      <br>

      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
        <div class="btn-group" role="group" aria-label="Group with two button">
          <a href="{% url 'reception:visit-update' pk=visit.id %}" class="btn btn-secondary">
            Update
          </a>
          <a href="{% url 'reception:visit-delete' pk=visit.id %}" class="btn btn-danger">
            Delete
          </a>
        </div>

      </div>
    </div>
  </div>

{% endblock %}

templates/reception/visit_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}<title>{{ object|yesno:"Update,Create" }} a visit • ToTheDoctor</title>{% endblock %}

{% block content %}
  <br>
  <div class="container-fluid px-0">
    <div class="row">
      <div class="col">
        {% if visit %}
          <a href="{% url 'reception:visit-detail' pk=visit.id %}" class="btn btn-outline-primary">
            < Back
          </a>
        {% else %}
          <a href="{% url 'reception:visit-list' %}" class="btn btn-outline-primary">
            < Back
          </a>
        {% endif %}
      </div>

      <div class="col">
        <h2 class="text-center">{{ object|yesno:"Update,Create" }} a visit</h2>
      </div>
    </div>

    <br><br>
    <div class="mx-5 px-5">
      <form action="" method="post" novalidate>
        {% csrf_token %}
          {{ form|crispy }}
        <br>
        <input class="btn btn-primary mr-2" type="submit" value="Submit">
        <input class="btn btn-secondary" type="reset" value="Reset">
      </form>
    </div>

  </div>

{% endblock %}

templates/reception/visit_list.html
{% extends "base.html" %}

{% block title %}<title>List of visits • ToTheDoctor</title>{% endblock %}

{% block content %}
  <br>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <a href="{% url 'reception:index' %}" role="button" class="btn btn-outline-primary">
        < Back
      </a>
      </div>

      <div class="col">
        <h2 class="text-center">List of visits</h2>
      </div>

      <div class="col">
        <a href="{% url 'reception:visit-create' %}" class="btn btn-primary link-to-page">
          Create a new visit
        </a>
      </div>
    </div>

    {% include "includes/search.html" %}

    <div class="row border-bottom px-0">
      <div class="col">
        {% if visit_list %}
        <table class="table table-borderless table-hover">
          <thead class="thead-light border-top">
            <tr>
              <th scope="col">Date/Time visit</th>
              <th scope="col">Doctor</th>
              <th scope="col">Patient</th>
              <th scope="col">Treatment direction</th>
              <th scope="col">Type of visit</th>
              <th scope="col">#</th>
            </tr>
          </thead>
          {% for visit in visit_list %}
            <tbody>
              <tr>
                <td>
                  <a href="{% url 'reception:visit-detail' pk=visit.id %}" class="text-warning">
                    {{ visit.date_time }}
                  </a>
                </td>
                <td>{{ visit.doctor }}</td>
                <td>{{ visit.patient }}</td>
                <td>{{ visit.treatment_direction }}</td>
                <td>{{ visit.get_type_of_visit_display }}</td>
                <td>{{ visit.id }}</td>
              </tr>
            </tbody>
          {% endfor %}
        </table>
        {% else %}
          {% include "includes/fail_request.html" %}
        {% endif %}
      </div>
    </div>

  </div>

{% endblock %}