config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reception.urls", namespace="reception")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("users/", include("users.urls", namespace="user")),
]

reception/urls.py
from django.urls import path

from .views import (
    index,
    VisitListView,
    VisitDetailView,
    VisitCreateView,
    VisitUpdateView,
    VisitDeleteView,
)

app_name = "reception"

urlpatterns = [
    path("", index, name="index"),
    path("visits/", VisitListView.as_view(), name="visit-list"),
    path("visits/<int:pk>/", VisitDetailView.as_view(), name="visit-detail"),
    path("visits/create/", VisitCreateView.as_view(), name="visit-create"),
    path(
        "visits/<int:pk>/update/",
        VisitUpdateView.as_view(),
        name="visit-update",
    ),
    path(
        "visits/<int:pk>/delete/",
        VisitDeleteView.as_view(),
        name="visit-delete",
    ),
]

users/urls.py
from django.urls import path

from .views import (
    PatientListView,
    PatientDetailView,
    PatientCreateView,
    PatientUpdateView,
    PatientDeleteView,
    DoctorListView,
    DoctorDetailView,
    DoctorCreateView,
    DoctorUpdateView,
    DoctorDeleteView,
)

app_name = "user"

urlpatterns = [
    path("patients/", PatientListView.as_view(), name="patient-list"),
    path(
        "patients/<int:pk>/",
        PatientDetailView.as_view(),
        name="patient-detail",
    ),
    path(
        "patients/create/", PatientCreateView.as_view(), name="patient-create"
    ),
    path(
        "patients/<int:pk>/update/",
        PatientUpdateView.as_view(),
        name="patient-update",
    ),
    path(
        "patients/<int:pk>/delete/",
        PatientDeleteView.as_view(),
        name="patient-delete",
    ),
    path("doctors/", DoctorListView.as_view(), name="doctor-list"),
    path(
        "doctors/<int:pk>/", DoctorDetailView.as_view(), name="doctor-detail"
    ),
    path("doctors/create/", DoctorCreateView.as_view(), name="doctor-create"),
    path(
        "doctors/<int:pk>/update/",
        DoctorUpdateView.as_view(),
        name="doctor-update",
    ),
    path(
        "doctors/<int:pk>/delete/",
        DoctorDeleteView.as_view(),
        name="doctor-delete",
    ),
]

templates/includes/fail_request.html
<div class="alert alert-warning" role="alert">
  Nothing was found for your request. Please, try changing your request
</div>

templates/includes/footer.html
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4">
  <p class="col-md-4 mb-0 text-muted">© 2023 • ToTheDoctor</p>
  <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
    <svg class="bi me-2" width="40" height="32">
      <img src="/static/image/logo.png" width="50" height="50">
    </svg>
  </a>
  <ul class="nav col-md-4 justify-content-end">
    <li class="nav-item">
      <a href="{% url 'reception:index' %}" class="nav-link px-2 text-muted">Home</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'reception:visit-list' %}" class="nav-link px-2 text-muted">Visits</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'user:doctor-list' %}" class="nav-link px-2 text-muted">Doctors</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'user:patient-list' %}" class="nav-link px-2 text-muted">Patients</a>
    </li>
  </ul>
</footer>

templates/includes/header.html
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
    <div class="container-fluid">
      <span class="navbar-brand">
        <img src="/static/image/logo.png" width="40" height="40" class="d-inline-block align-top">
      </span>

      <span class="navbar-brand mb-0 h1">ToTheDoctor</span>

      <div class="collapse navbar-collapse">
        <div class="navbar-nav ms-auto">
          <a class="nav-link" href="{% url 'reception:index' %}">Home</a>
          <a class="nav-link" href="{% url 'reception:visit-list' %}">Visits</a>
          <a class="nav-link" href="{% url 'user:doctor-list' %}">Doctors</a>
          <a class="nav-link" href="{% url 'user:patient-list' %}">Patients</a>
        </div>
      </div>

      {% if is_show_counter %}
        <span class="text-warning bg-dark mr-sm-5">
          <small>
            You have visited this page <strong>{{ num_visit_page }}</strong> time{{ num_visit_page|pluralize }}
          </small>
        </span>
      {% endif %}

      <form class="form-inline">
        <a class="btn btn-outline-warning mr-sm-2 disabled" href="{{ get_absolute_url }}">{{ user.get_username }}</a>
        <a class="btn btn-outline-secondary mr-sm-5" href="{% url 'logout'%}?next={{request.path}}" role="button">
          Logout
        </a>
        <a class="navbar-brand" href="https://github.com/OleksiiKiva/to-the-doctor.git">
          <img src="/static/image/github.png" alt width="40" height="40">
        </a>
      </form>

    </div>
  </nav>
</header>

templates/includes/pagination.html
{% load query_transform %}

<br><br>
{% if is_paginated %}
<ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a class="page-link text-dark" href="?{% query_transform request page=page_obj.previous_page_number %}">
      &laquo;</a>
  </li>
  {% endif %}

  <li class="page-item">
    <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
  </li>

  {% if page_obj.has_next %}
  <li class="page-item">
    <a class="page-link text-dark" href="?{% query_transform request page=page_obj.next_page_number %}">
      &raquo;</a>
  </li>
  {% endif %}

</ul>
{% endif %}

templates/includes/search.html
{% load crispy_forms_filters %}

<br><br>
<nav class="navbar px-0">
  <span></span>
  <form class="form-inline">
    {{ search_form|crispy }}
    <button class="btn btn-outline-warning ml-3" type="submit">Search</button>
  </form>
</nav>
<br>