config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reception.urls", namespace="reception")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("users/", include("users.urls", namespace="user")),
]

reception/urls.py
from django.urls import path

from .views import (
    index,
    VisitListView,
    VisitDetailView,
    VisitCreateView,
    VisitUpdateView,
    VisitDeleteView,
)

app_name = "reception"

urlpatterns = [
    path("", index, name="index"),
    path("visits/", VisitListView.as_view(), name="visit-list"),
    path("visits/<int:pk>/", VisitDetailView.as_view(), name="visit-detail"),
    path("visits/create/", VisitCreateView.as_view(), name="visit-create"),
    path(
        "visits/<int:pk>/update/",
        VisitUpdateView.as_view(),
        name="visit-update",
    ),
    path(
        "visits/<int:pk>/delete/",
        VisitDeleteView.as_view(),
        name="visit-delete",
    ),
]

users/urls.py
from django.urls import path

from .views import (
    PatientListView,
    PatientDetailView,
    PatientCreateView,
    PatientUpdateView,
    PatientDeleteView,
    DoctorListView,
    DoctorDetailView,
    DoctorCreateView,
    DoctorUpdateView,
    DoctorDeleteView,
)

app_name = "user"

urlpatterns = [
    path("patients/", PatientListView.as_view(), name="patient-list"),
    path(
        "patients/<int:pk>/",
        PatientDetailView.as_view(),
        name="patient-detail",
    ),
    path(
        "patients/create/", PatientCreateView.as_view(), name="patient-create"
    ),
    path(
        "patients/<int:pk>/update/",
        PatientUpdateView.as_view(),
        name="patient-update",
    ),
    path(
        "patients/<int:pk>/delete/",
        PatientDeleteView.as_view(),
        name="patient-delete",
    ),
    path("doctors/", DoctorListView.as_view(), name="doctor-list"),
    path(
        "doctors/<int:pk>/", DoctorDetailView.as_view(), name="doctor-detail"
    ),
    path("doctors/create/", DoctorCreateView.as_view(), name="doctor-create"),
    path(
        "doctors/<int:pk>/update/",
        DoctorUpdateView.as_view(),
        name="doctor-update",
    ),
    path(
        "doctors/<int:pk>/delete/",
        DoctorDeleteView.as_view(),
        name="doctor-delete",
    ),
]

users/models.py
from datetime import date

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from utils.models import SoftDeleteModel


class Specialization(SoftDeleteModel):
    name = models.CharField(max_length=30)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Doctor(AbstractUser, SoftDeleteModel):
    recertification_with = models.DateField(default=date.today)
    specializations = models.ManyToManyField(
        Specialization, related_name="doctors"
    )

    class Meta:
        ordering = ("last_name",)
        verbose_name = "doctor"
        verbose_name_plural = "doctors"

    def __str__(self):
        return f"{self.last_name} {self.first_name}"

    def get_absolute_url(self):
        return reverse("user:doctor-detail", kwargs={"pk": self.pk})


class Patient(SoftDeleteModel):
    phone_number = models.CharField(max_length=10, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_of_birth = models.DateField(default=date.today)

    class Meta:
        ordering = ("last_name",)

    def __str__(self):
        return f"{self.last_name} {self.first_name}"

    def get_absolute_url(self):
        return reverse("user:patient-detail", kwargs={"pk": self.pk})

users/forms.py
from datetime import date, timedelta

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from users.models import Doctor, Specialization, Patient


class UserSearchForm(forms.Form):
    last_name = forms.CharField(
        max_length=10,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by last name"}),
    )


class PatientForm(forms.ModelForm):
    class Meta(UserCreationForm.Meta):
        model = Patient
        fields = (
            "first_name",
            "last_name",
            "phone_number",
            "date_of_birth",
        )

    def clean_date_of_birth(self):
        return validate_date_of_birth(self.cleaned_data["date_of_birth"])


def validate_date_of_birth(date_of_birth):
    """
    The function that checks the date of birth field.
    Patients must be at least six months old.
    """
    if date_of_birth >= date.today() - timedelta(6 * 365 / 12):
        raise ValidationError(
            "Date of birth less than 6 months. "
            "Patients in this age group are not served."
        )

    return date_of_birth


class DoctorForm(UserCreationForm):
    specializations = forms.ModelMultipleChoiceField(
        queryset=Specialization.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta(UserCreationForm.Meta):
        model = Doctor
        fields = (
            "first_name",
            "last_name",
            "email",
            "specializations",
            "recertification_with",
            "username",
            "password1",
            "password2",
        )

    def clean_recertification_with(self):
        return validate_recertification_with(
            self.cleaned_data["recertification_with"]
        )


def validate_recertification_with(recertification_with):
    """
    Check the validity period of the doctor's certificate.
    The date on the certificate must be greater than the current date.
    """
    if recertification_with <= date.today():
        raise ValidationError(
            "The date has expired. "
            "Please enter correct data in YYYY-MM-DD format"
        )

    return recertification_with

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from users.forms import UserSearchForm, DoctorForm, PatientForm
from users.models import Doctor, Patient


class PatientListView(LoginRequiredMixin, generic.ListView):
    model = Patient
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PatientListView, self).get_context_data(**kwargs)
        last_name = self.request.GET.get("last_name", "")
        context["search_form"] = UserSearchForm(
            initial={"last_name": last_name}
        )
        return context

    def get_queryset(self):
        queryset = Patient.objects.filter(deleted_at__isnull=True)
        form = UserSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                last_name__icontains=form.cleaned_data["last_name"]
            )

        return queryset


class PatientDetailView(LoginRequiredMixin, generic.DetailView):
    model = Patient
    queryset = Patient.objects.filter(deleted_at__isnull=True)


class PatientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Patient
    form_class = PatientForm
    success_url = reverse_lazy("user:patient-list")


class PatientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Patient
    form_class = PatientForm
    success_url = reverse_lazy("user:patient-list")


class PatientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Patient
    success_url = reverse_lazy("user:patient-list")


class DoctorListView(LoginRequiredMixin, generic.ListView):
    model = Doctor
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DoctorListView, self).get_context_data(**kwargs)
        last_name = self.request.GET.get("last_name", "")
        context["search_form"] = UserSearchForm(
            initial={"last_name": last_name}
        )
        return context

    def get_queryset(self):
        queryset = (
            Doctor.objects.prefetch_related("specializations")
            .filter(is_staff=False)
            .filter(deleted_at__isnull=True)
        )
        form = UserSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                last_name__icontains=form.cleaned_data["last_name"]
            )

        return queryset


class DoctorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Doctor
    queryset = Doctor.objects.prefetch_related("specializations")


class DoctorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Doctor
    form_class = DoctorForm
    success_url = reverse_lazy("user:doctor-list")


class DoctorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Doctor
    form_class = DoctorForm
    success_url = reverse_lazy("user:doctor-list")


class DoctorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Doctor
    success_url = reverse_lazy("user:doctor-list")

templates/users/doctor_confirm_delete.html
{% extends "base.html" %}

{% block title %}<title>Doctor confirm delete • ToTheDoctor</title>{% endblock %}

{% block content %}
  <br>
  <a href="{% url 'user:doctor-detail' pk=doctor.id %}" class="btn btn-outline-primary">
    < Back
  </a>

  <div class="px-4 pt-5 my-5 text-center border-top border-bottom">
    <h1 class="display-4 fw-bold text-body-emphasis">
      Do you want to delete all information about
      <span class="text-muted">{{ doctor.first_name }} {{ doctor.last_name }}</span>?
    </h1>
    <br>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
      <form action="" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Yes, delete">
      </form>
    </div>

  </div>

{% endblock %}

templates/users/doctor_detail.html
{% extends "base.html" %}

{% block title %}<title>Doctor details • ToTheDoctor</title>{% endblock %}

{% block content %}
  <br>
    <a href="{% url 'user:doctor-list' %}" class="btn btn-outline-primary">
      < Back
    </a>
  <br>
  <br>
  <br>

    <div class="row">
      <br>
      <div class="col-md-5">
        <img src="/static/picture/doctors/doctor.png"
             class="img-fluid border border-secondary" width="100%">
      </div>

      <div class="col-md-2"></div>

      <div class="col-md-5">
        <h2 class="font-weight-normal">
          {{ doctor.first_name }} {{ doctor.last_name }}
        </h2>
        <br>

        <p>Specialization:
          {% for specialization in doctor.specializations.all %}
            <span class="text-muted">{{ specialization }}</span>
          {% endfor %}
        </p>

        <p>Certificate up to:
          <span class="text-muted">{{ doctor.recertification_with }}</span>
        </p>


        <p class="font-weight-light text-muted">username:
          <span class="font-weight-normal">{{ doctor.username }}</span>
        </p>

        <p class="font-weight-light text-muted">e-mail:
          <span class="font-weight-normal">{{ doctor.email }}</span>
        </p>
        <br>

        {% if doctor.visits.first and doctor.visits.first.patient.deleted_at is None %}
          {% now "o-j-N" as today_date %}
          {% if today_date < doctor.visits.first.date_time|date:"o-j-N" %}
            <p class="font-weight-light text-muted border-top">Nearest visit:
              <span class="font-weight-normal">{{ doctor.visits.first.date_time }}</span>
            </p>

            <p class="font-weight-light text-muted border-bottom">Patient:
              <a href="{% url 'user:patient-detail' pk=doctor.visits.last.patient.id %}" class="text-warning">
                {{ doctor.visits.first.patient }}
                {{ doctor.visits.first.date_time|date:"o-j-N" }}
              </a>
            </p>
          {% endif %}
        {% endif %}
        <br>
        <br>

        {% if user.is_staff %}
        <div class="btn-group" role="group" aria-label="Group with two button">
            <a href="{% url 'user:doctor-update' pk=doctor.id %}" class="btn btn-secondary">
              Update
            </a>
            <a href="{% url 'user:doctor-delete' pk=doctor.id %}" class="btn btn-danger">
              Delete
            </a>
        </div>
        {% endif %}

      </div>

    </div>

{% endblock %}

templates/users/doctor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}<title>{{ object|yesno:"Update,Create" }} a doctor • ToTheDoctor</title>{% endblock %}

{% block content %}
  <br>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        {% if doctor %}
          <a href="{% url 'user:doctor-detail' pk=doctor.id %}" class="btn btn-outline-primary">
            < Back
          </a>
        {% else %}
          <a href="{% url 'user:doctor-list' %}" class="btn btn-outline-primary">
            < Back
          </a>
        {% endif %}
      </div>

      <div class="col">
        <h2 class="text-center">{{ object|yesno:"Update,Create" }} a doctor</h2>
      </div>
    </div>

    <br><br>
    <nav class="mx-5 px-5">
      <form action="" method="post" novalidate>
        {% csrf_token %}
          {{ form|crispy }}
        <br>
        <input class="btn btn-primary mr-2" type="submit" value="Submit">
        <input class="btn btn-secondary" type="reset" value="Reset">
      </form>
    </nav>

  </div>

{% endblock %}

templates/users/doctor_list.html
{% extends "base.html" %}

{% block title %}<title>List of doctors • ToTheDoctor</title>{% endblock %}

{% block content %}
  <br>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <a href="{% url 'reception:index' %}" role="button" class="btn btn-outline-primary">
        < Back
      </a>
      </div>

      <div class="col">
        <h2 class="text-center">List of doctors</h2>
      </div>

      {% if user.is_staff %}
        <div class="col">
          <a href="{% url 'user:doctor-create' %}" class="btn btn-primary link-to-page">
            Create a doctor
          </a>
        </div>
      {% endif %}

    </div>

    {% include "includes/search.html" %}

    <div class="row border-bottom px-0">
      <div class="col">
        <br>
        <br>
        {% if doctor_list %}
        <table class="table table-borderless table-hover">
          <thead class="thead-light border-top">
            <tr>
              <th scope="col">Doctor</th>
              <th scope="col">Specialization</th>
              <th scope="col">Certificate up to</th>
              <th scope="col">Username</th>
              <th scope="col">E-mail</th>
              <th scope="col">#</th>
            </tr>
          </thead>
          {% for doctor in doctor_list %}
          <tbody>
            <tr>
              <td>
                <a href="{% url 'user:doctor-detail' pk=doctor.id %}" class="text-warning">
                  {{ doctor.first_name }} {{ doctor.last_name }}
                </a>
              </td>
              <td>
                {% for specialization in doctor.specializations.all %}
                  {{ specialization }}
                {% endfor %}
              </td>
              <td>{{ doctor.recertification_with }}</td>
              <td>{{ doctor.username }}</td>
              <td>{{ doctor.email }}</td>
              <td>{{ doctor.id }}</td>
            </tr>
          </tbody>
          {% endfor %}
        </table>
        {% else %}
          {% include "includes/fail_request.html" %}
        {% endif %}
      </div>
    </div>

  </div>

{% endblock %}

templates/users/patient_confirm_delete.html
{% extends "base.html" %}

{% block title %}<title>Patient confirm delete • ToTheDoctor</title>{% endblock %}

{% block content %}
  <br>
  <a href="{% url 'user:patient-detail' pk=patient.id %}" class="btn btn-outline-primary">
    < Back
  </a>

  <div class="px-4 pt-5 my-5 text-center border-top border-bottom">
    <h1 class="display-4 fw-bold text-body-emphasis">
      Do you want to delete all information about
      <span class="text-muted">{{ patient.first_name }} {{ patient.last_name }}</span>?
    </h1>
    <br>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
      <form action="" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Yes, delete">
      </form>
    </div>

  </div>

{% endblock %}

templates/users/patient_detail.html
{% extends "base.html" %}

{% block title %}<title>Patient details • ToTheDoctor</title>{% endblock %}

{% block content %}
  <br>
    <a href="{% url 'user:patient-list' %}" class="btn btn-outline-primary">
      < Back
    </a>
  <br>
  <br>
  <br>

  <div class="row">
    <div class="col-md-5">
      <img src="/static/picture/patients/patient.png"
           class="img-fluid border border-secondary" width="100%">
    </div>

    <div class="col-md-2"></div>

    <div class="col-md-5">
      <h2 class="font-weight-normal">
        {{ patient.first_name }} {{ patient.last_name }}
      </h2>
      <br>

      <p>Phone number:
        <span class="text-muted">{{ patient.phone_number }}</span>
      </p>


      <p class="font-weight-light text-muted">Date of birth:
        <span class="font-weight-normal">{{ patient.date_of_birth }}</span>
      </p>
      <br>

      {% if patient.visits.last and patient.visits.last.doctor.deleted_at is none %}
        <p class="font-weight-light text-muted border-top">Nearest visit:
          <span class="font-weight-normal">{{ patient.visits.last.date_time }}</span>
        </p>

        <p class="font-weight-light text-muted border-bottom">Doctor:
          <a href="{% url 'user:doctor-detail' pk=patient.visits.last.doctor.id %}" class="text-warning">
            {{ patient.visits.last.doctor }}
          </a>
        </p>
      {% endif %}
      <br>
      <br>
      <br>

      <div class="btn-group" role="group" aria-label="Group with two button">
          <a href="{% url 'user:patient-update' pk=patient.id %}" class="btn btn-secondary">
            Update
          </a>
          <a href="{% url 'user:patient-delete' pk=patient.id %}" class="btn btn-danger">
            Delete
          </a>
      </div>
    </div>
  </div>

{% endblock %}

templates/users/patient_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}<title>{{ object|yesno:"Update,Create" }} a patient • ToTheDoctor</title>{% endblock %}

{% block content %}
  <br>
  <div class="container-fluid px-0">
    <div class="row">
      <div class="col">
        {% if patient %}
          <a href="{% url 'user:patient-detail' pk=patient.id %}" class="btn btn-outline-primary">
            < Back
          </a>
        {% else %}
          <a href="{% url 'user:patient-list' %}" class="btn btn-outline-primary">
            < Back
          </a>
        {% endif %}
      </div>

      <div class="col">
        <h2 class="text-center">{{ object|yesno:"Update,Create" }} a patient</h2>
      </div>
    </div>

    <br><br>
    <nav class="mx-5 px-5">
      <form action="" method="post" novalidate>
        {% csrf_token %}
          {{ form|crispy }}
        <br>
        <input class="btn btn-primary mr-2" type="submit" value="Submit">
        <input class="btn btn-secondary" type="reset" value="Reset">
      </form>
    </nav>

  </div>

{% endblock %}

templates/users/patient_list.html
{% extends "base.html" %}

{% block title %}<title>List of patients • ToTheDoctor</title>{% endblock %}

{% block content %}
  <br>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <a href="{% url 'reception:index' %}" role="button" class="btn btn-outline-primary">
        < Back
      </a>
      </div>

      <div class="col">
        <h2 class="text-center">List of patients</h2>
      </div>

      <div class="col">
        <a href="{% url 'user:patient-create' %}" class="btn btn-primary link-to-page">
          Create a patient
        </a>
      </div>
    </div>

    {% include "includes/search.html" %}

    <div class="row border-bottom px-0">
      <div class="col">
        <br>
        <br>
        {% if patient_list %}
        <table class="table table-borderless table-hover">
          <thead class="thead-light border-top">
            <tr>
              <th scope="col">Patient</th>
              <th scope="col">Phone number</th>
              <th scope="col">Date of birth</th>
              <th scope="col">#</th>
            </tr>
          </thead>
          {% for patient in patient_list %}
          <tbody>
            <tr>
              <td>
                <a href="{% url 'user:patient-detail' pk=patient.id %}" class="text-warning">
                  {{ patient.first_name }} {{ patient.last_name }}
                </a>
              </td>
              <td>{{ patient.phone_number }}</td>
              <td>{{ patient.date_of_birth }}</td>
              <td>{{ patient.id }}</td>
            </tr>
          </tbody>
          {% endfor %}
        </table>
        {% else %}
          {% include "includes/fail_request.html" %}
        {% endif %}
      </div>
    </div>

  </div>

{% endblock %}